version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: /before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /after_start.sh
      timeout: 300
      runas: root